source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-formhelpers'
gem 'sinatra-simple-auth'
gem 'fssm'
gem 'thin'
gem 'rspec'
gem 'log4r'
gem 'rake'
gem 'sys-proctable'
gem 'jeweler'
gem 'dante'
